### ISSUE TITLE
Avoid using setup-r-dependencies

### ISSUE THREAD

**Issue by Anirban166** [Anirban166/Autocomment-GA#2]
Note that it's better to manually install dependencies (like I'm currently doing, 4ab0eed) instead of using `setup-r-dependencies@<version>` since `pak` is based on package installations from source/binary, and might require a pre-defined setup of dependent R packages to avoid conflicts.
```yml
    - name: setup-dependency
      uses: r-lib/actions/setup-r-dependencies@v2
      with:
        extra-packages: any::devtools, any::ggplot2, any::directlabels
        needs: check
```
```sh
Error: 
 ! error in pak subprocess
 Caused by error: 
 ! Could not solve package dependencies:
 * deps::.: ! pkgdepends resolution error for deps::..
 Caused by error: 
 ! Could not find R package in `.` or its parent directories.
 * any::sessioninfo: dependency conflict
 * any::devtools: dependency conflict
 * any::ggplot2: dependency conflict
 * any::directlabels: dependency conflict
 ---
 Backtrace:
 1. pak::lockfile_create(c(deps, extra_deps), lockfile = ".github/pkg.lock", …
 2. pak:::remote(function(...) { …
 3. err$throw(res$error)
 ---
 Subprocess backtrace:
 1. base::withCallingHandlers(cli_message = function(msg) { …
 2. get("lockfile_create_internal", asNamespace("pak"))(...)
 3. prop$stop_for_solution_error()
 4. private$plan$stop_for_solve_error()
 5. pkgdepends:::pkgplan_stop_for_solve_error(self, private)
 6. base::throw(new_error("Could not solve package dependencies:\n", msg, …
 7. | base::signalCondition(cond)
 8. global (function (e) …
 Execution halted        
```
